[project]
name = "pixi-lightning"
version = "0.1.0"
description = "PyTorch template with pixi, Lightning, W&B"
authors = ["Sungdon Kim <sehandev@gmail.com>"]
channels = ["conda-forge", "pytorch", "nvidia"]
platforms = ["linux-64"]

[tasks]
test_pytorch = "python test/torch.py"
train = "python train.py"

[dependencies]
python = "3.8.*"
torchvision = "0.15.2.*"
lightning = "2.0.7.*"
torchaudio = "2.0.2.*"
pytorch = "2.0.1.*"
pytorch-cuda = "11.7.*"
rich = "13.5.1.*"
wandb = "0.15.8.*"
